"""initial schema

Revision ID: 3e163bfcd88a
Revises: 
Create Date: 2026-10-07 11:44:47.394795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


revision: str = '3e163bfcd88a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_districts_slug'), ['slug'], unique=True)

    op.create_table('milestone_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('qualifying_count', sa.Integer(), nullable=False),
    sa.Column('pending_opportunity', sa.Boolean(), nullable=False),
    sa.Column('last_opportunity_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestone_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_progress_key'), ['key'], unique=True)

    op.create_table('simulation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('elapsed_minutes', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_logs_ran_at'), ['ran_at'], unique=False)

    op.create_table('story_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story_milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_milestones_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active_character_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_active_character_id'), ['active_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_date', sa.Date(), nullable=False),
    sa.Column('current_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('last_simulated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('last_catchup_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('city_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_state_current_date'), ['current_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_state_last_simulated_at'), ['last_simulated_at'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('activities', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_locations_slug'), ['slug'], unique=True)

    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('pronouns', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('profession_label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('is_npc', sa.Boolean(), nullable=False),
    sa.Column('personality', sa.JSON(), nullable=False),
    sa.Column('communication_style', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('hobbies', sa.JSON(), nullable=False),
    sa.Column('likes', sa.JSON(), nullable=False),
    sa.Column('dislikes', sa.JSON(), nullable=False),
    sa.Column('goals', sa.JSON(), nullable=False),
    sa.Column('flaws', sa.JSON(), nullable=False),
    sa.Column('favorite_location_ids', sa.JSON(), nullable=False),
    sa.Column('money', sa.Float(), nullable=False),
    sa.Column('discovered_level', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_current_location_id'), ['current_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_is_npc'), ['is_npc'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_photo_id'), ['photo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('employer_location_id', sa.Integer(), nullable=True),
    sa.Column('salary_per_shift', sa.Float(), nullable=False),
    sa.Column('schedule_template', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['employer_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_employer_location_id'), ['employer_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=True)

    op.create_table('character_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_jobs_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_character_jobs_job_id'), ['job_id'], unique=False)

    op.create_table('character_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_photos_character_id'), ['character_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_a_id', sa.Integer(), nullable=False),
    sa.Column('character_b_id', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_a_id', 'character_b_id', name='uq_conversation_pair')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_character_a_id'), ['character_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_character_b_id'), ['character_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_last_message_at'), ['last_message_at'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('host_character_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('scheduled_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_host_character_id'), ['host_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_character_id', sa.Integer(), nullable=False),
    sa.Column('followed_character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['follower_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_character_id', 'followed_character_id', name='uq_follow_pair')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_followed_character_id'), ['followed_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_character_id'), ['follower_character_id'], unique=False)

    op.create_table('future_hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_character_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('due_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('future_hooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_future_hooks_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_future_hooks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_future_hooks_target_character_id'), ['target_character_id'], unique=False)

    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'character_id', name='uq_like_target')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_target_type'), ['target_type'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('read_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)

    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_a_id', sa.Integer(), nullable=False),
    sa.Column('character_b_id', sa.Integer(), nullable=False),
    sa.Column('familiarity', sa.Integer(), nullable=False),
    sa.Column('friendship', sa.Integer(), nullable=False),
    sa.Column('trust', sa.Integer(), nullable=False),
    sa.Column('romance', sa.Integer(), nullable=False),
    sa.Column('respect', sa.Integer(), nullable=False),
    sa.Column('tension', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_a_id', 'character_b_id', name='uq_relationship_pair')
    )
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relationships_character_a_id'), ['character_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_character_b_id'), ['character_b_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relationships_last_interaction_at'), ['last_interaction_at'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('activity', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_location_id'), ['location_id'], unique=False)

    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('ended_reason', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_sessions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_sessions_status'), ['status'], unique=False)

    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('responded_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('joined_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'character_id', name='uq_event_participant')
    )
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_participants_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_participants_event_id'), ['event_id'], unique=False)

    op.create_table('event_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_character_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('ended_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('resume_count', sa.Integer(), nullable=False),
    sa.Column('outcome_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['player_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'player_character_id', name='uq_event_session')
    )
    with op.batch_alter_table('event_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_sessions_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_sessions_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_sessions_player_character_id'), ['player_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_sessions_status'), ['status'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_character_id', sa.Integer(), nullable=False),
    sa.Column('other_character_id', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['other_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_other_character_id'), ['other_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_owner_character_id'), ['owner_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_source_event_id'), ['source_event_id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_character_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_author_character_id'), ['author_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_location_id'), ['location_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_character_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_character_id'), ['author_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    op.create_table('event_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('relationship_changes', sa.JSON(), nullable=False),
    sa.Column('memories', sa.JSON(), nullable=False),
    sa.Column('social_effects', sa.JSON(), nullable=False),
    sa.Column('future_hooks', sa.JSON(), nullable=False),
    sa.Column('applied_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_outcomes_session_id'), ['session_id'], unique=True)

    op.create_table('event_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('narrative', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=False),
    sa.Column('dialogue', sa.JSON(), nullable=False),
    sa.Column('available_actions', sa.JSON(), nullable=False),
    sa.Column('player_action_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('player_action_label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['event_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_index', name='uq_event_turn')
    )
    with op.batch_alter_table('event_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_turns_session_id'), ['session_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('sender_character_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_character_id'), ['sender_character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_character_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('event_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_turns_session_id'))

    op.drop_table('event_turns')
    with op.batch_alter_table('event_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_outcomes_session_id'))

    op.drop_table('event_outcomes')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_comments_author_character_id'))

    op.drop_table('comments')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_location_id'))
        batch_op.drop_index(batch_op.f('ix_posts_event_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_posts_author_character_id'))

    op.drop_table('posts')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_memories_owner_character_id'))
        batch_op.drop_index(batch_op.f('ix_memories_other_character_id'))
        batch_op.drop_index(batch_op.f('ix_memories_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_memories_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_memories_category'))

    op.drop_table('memories')
    with op.batch_alter_table('event_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_event_sessions_player_character_id'))
        batch_op.drop_index(batch_op.f('ix_event_sessions_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_event_sessions_event_id'))

    op.drop_table('event_sessions')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_participants_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_participants_character_id'))

    op.drop_table('event_participants')
    with op.batch_alter_table('conversation_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_conversation_sessions_conversation_id'))

    op.drop_table('conversation_sessions')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_location_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_character_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_last_interaction_at'))
        batch_op.drop_index(batch_op.f('ix_relationships_character_b_id'))
        batch_op.drop_index(batch_op.f('ix_relationships_character_a_id'))

    op.drop_table('relationships')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_character_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_target_type'))
        batch_op.drop_index(batch_op.f('ix_likes_target_id'))
        batch_op.drop_index(batch_op.f('ix_likes_character_id'))

    op.drop_table('likes')
    with op.batch_alter_table('future_hooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_future_hooks_target_character_id'))
        batch_op.drop_index(batch_op.f('ix_future_hooks_status'))
        batch_op.drop_index(batch_op.f('ix_future_hooks_due_at'))

    op.drop_table('future_hooks')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_character_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followed_character_id'))

    op.drop_table('follows')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_events_location_id'))
        batch_op.drop_index(batch_op.f('ix_events_host_character_id'))
        batch_op.drop_index(batch_op.f('ix_events_created_at'))

    op.drop_table('events')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_last_message_at'))
        batch_op.drop_index(batch_op.f('ix_conversations_character_b_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_character_a_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('character_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_photos_character_id'))

    op.drop_table('character_photos')
    with op.batch_alter_table('character_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_jobs_job_id'))
        batch_op.drop_index(batch_op.f('ix_character_jobs_character_id'))

    op.drop_table('character_jobs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title'))
        batch_op.drop_index(batch_op.f('ix_jobs_employer_location_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_user_id'))
        batch_op.drop_index(batch_op.f('ix_characters_photo_id'))
        batch_op.drop_index(batch_op.f('ix_characters_name'))
        batch_op.drop_index(batch_op.f('ix_characters_is_npc'))
        batch_op.drop_index(batch_op.f('ix_characters_current_location_id'))
        batch_op.drop_index(batch_op.f('ix_characters_created_at'))

    op.drop_table('characters')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_slug'))
        batch_op.drop_index(batch_op.f('ix_locations_name'))
        batch_op.drop_index(batch_op.f('ix_locations_district_id'))

    op.drop_table('locations')
    with op.batch_alter_table('world_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_state_last_simulated_at'))
        batch_op.drop_index(batch_op.f('ix_world_state_current_date'))

    op.drop_table('world_state')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_active_character_id'))

    op.drop_table('users')
    with op.batch_alter_table('story_milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_milestones_key'))

    op.drop_table('story_milestones')
    with op.batch_alter_table('simulation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_logs_ran_at'))

    op.drop_table('simulation_logs')
    with op.batch_alter_table('milestone_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_progress_key'))

    op.drop_table('milestone_progress')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_slug'))
        batch_op.drop_index(batch_op.f('ix_districts_name'))

    op.drop_table('districts')
    # ### end Alembic commands ###
